version: "3.9"
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./tmp/db:/root/db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/geolocation-api
    ports:
      - "3000:3000"
    depends_on:
      - db
